# https://github.com/bitnami/charts/tree/main/bitnami/postgresql
load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://restart_process', 'docker_build_with_restart')
load('ext://secret', 'secret_create_generic', 'secret_from_dict')


def postgres(password="password", port_forwards=[5432], labels=['database']):
    k8s_yaml(secret_from_dict("tilt-pg", inputs = {
        'postgres-password' : password
    }))

    current_dir = os.path.dirname(__file__)
    yaml_path = os.path.join(current_dir, 'postgres.yaml')
    k8s_yaml(yaml_path)
    k8s_resource('postgres', port_forwards=port_forwards, labels=["database"])
