apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      enableServiceLinks: false
      containers:
      - name: redpanda
        image: redpandadata/redpanda:v24.2.18
        ports:
        - containerPort: 9092
        - containerPort: 9644 # Admin API
        args:
        - redpanda
        - start
        - --smp 1
        - --reserve-memory 0M
        - --overprovisioned
        - --node-id 0
        - --check=false
        - --advertise-kafka-addr=redpanda:9092
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
  - name: redpanda
    port: 9092
    targetPort: 9092
  - name: admin
    port: 9644
    targetPort: 9644
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
data:
  redpanda.yaml: |
    enable_auto_creation: true
