load('ext://restart_process', 'docker_build_with_restart')

def redpanda():
    """
    Run a Redpanda instance. This is a drop-in replacement for Kafka.
    """
    # TODO: https://docs.redpanda.com/current/get-started/docker-compose-labs/
    current_dir = os.path.dirname(__file__)
    yaml_path = os.path.join(current_dir, 'redpanda.yaml')
    k8s_yaml(yaml_path)
    k8s_resource('redpanda', port_forwards=[9092,9644])

    #run("kubectl exec -it redpanda-0 in redpanda -- rpk topic create demo")
    # kubectl exec -it redpanda-0 in redpanda -- bash
    # rpk topic create demo
    # rpk topic create turkey
    # rpk topic list