# https://github.com/bitnami/charts/tree/main/bitnami/mysql
load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://restart_process', 'docker_build_with_restart')
load('ext://secret', 'secret_create_generic', 'secret_from_dict')


def mysql(password="password", database_name="my_database", port_forwards=[3306], labels=['database']):
    k8s_yaml(secret_from_dict("tilt-mysql", inputs = {
        'mysql-password' : password,
        'mysql-root-password' : password,
        'mysql-replication-password' : password
    }))
    helm_repo('bitnami', 'https://charts.bitnami.com/bitnami', resource_name='mysql-bitnami')
    helm_resource(
        name='mysql',
        chart='bitnami/mysql',
        namespace='default',
        flags=[
            '--set=auth.existingSecret=tilt-mysql',
            '--set=auth.database=' + database_name,
            '--set=primary.persistence.enabled=false',
            '--set=fullnameOverride=mysql',
            '--set=primary.resourcesPreset=large',
        ],
        port_forwards=port_forwards,
        labels=labels,
    )